### PR TITLE
optimize cpu usage.

### PR DESCRIPTION
**Pull request by ys-pro-duction**
write some logic to repaint only when it's need and update time every second with partially repaint.
cpu load heavily goes down. #6

### CODE REVIEW

**Review by saharsh-agrawal — CHANGES_REQUESTED** [review]
Nice observation and approach, but pointing out a few things:
i) you dont need to start another thread in a a thread itself - run function itself runs in a thread. Another thread is completely unecessary and it works exactly the same without it also.
ii) although 1 sec is fine for he timer thing, the logic for detecting changing cell is somehow either taking too long or calculating wrong and hnce appears not very 'quick responsive' or glitchy or laggy.

Not repaintng the entire thing while(true) already reduces the the processing by A LOT even if you render the entire thing after 10 miliiseconds. So you can either come up with a soltion for the hover issue or maybe simply let the enitre thing render every 10 or 20 or 50 milliseconds - works just as fine in practical situations.

**Comment by ys-pro-duction** [comment]
> enitre thing render every 10 or 20 or 50 milliseconds.

it's not cpu friendly because it recalculate and rerender entire ui every millisecond even when ui is still same or user not interacting  with it.
you can compare this PR and [every 16 millisecond (~60fps) approach](https://github.com/ys-pro-duction/Minesweeper/tree/feature/repaintInMiliSe)

**Review by saharsh-agrawal — COMMENTED** [review]
I have checked both the options. The first one is stil a bit laggy and the second one is too cpu heavy. I guess a middle ground would be to let it be 1000 ms but take the repaint() out of the inners ifs and else in hover() and let it run simply in if(my > gap+titleBar), effectively overwriting the entire logic to find and check for lastMinX and lastMinY - effectively making it run for mouseMoved and mouseDragged (when if (my > gap+titleBar)).

**Comment by ys-pro-duction** [comment]
now it's work like a charm

**Review by saharsh-agrawal — APPROVED** [review]
yeah!

**Pull request merged**
